language: cpp
dist: bionic
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic -y
  - sudo apt-get update
  - git submodule update --init --recursive

install:
  - sudo apt-get install qt512base qt512svg qt512charts-no-lgpl
  - source /opt/qt512/bin/qt512-env.sh 


script:
  - git clone https://github.com/KDE/extra-cmake-modules.git
  - cd extra-cmake-modules
  - mkdir build && cd build    
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/
  - make && sudo make install
  - cd ../..
  - git clone https://github.com/KDE/karchive.git
  - cd karchive
  - mkdir build && cd build 
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/
  - make 
  - sudo make install
  - cd ../..
  - /opt/qt58/bin/qmake PREFIX=/usr
  - make 
  - # Generate AppImage
  - sudo apt-get -y install checkinstall
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir -p appdir/usr/bin ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - mv ./usr/local/bin/* ./usr/bin/ # Why is this needed despite PREFIX=/usr? Bug?
  - cp ./usr/share/icons/hicolor/48x48/apps/fastqt.png .
  - cp ./usr/share/applications/fastqt.desktop .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/htslib/
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -appimage 
  - curl --upload-file ./FastQt*.AppImage https://transfer.sh/FastQt-git.$(git rev-parse --short HEAD)-x86_64.AppImage 

# For gitter 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/de567d4879b8b044dfe7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# Temporarily disabled so that AppImage generation can be tested
# branches:
#   only:
#    - master
